### ISSUE TITLE
Demo repair

### ISSUE THREAD

**Issue by Iftikhar-Omar** [avored/avored-rust-cms#110]
I've deleted the admin user while trying demo. I was testing if there is any condition to leave at least one admin user at all times.

**Comment by indpurvesh** [comment]
@Iftikhar-Omar actually demo has not been changed for long time. Now i need to setup the node js server as front part is rendered via react app and backend is in rust axum api.  once i have some time will install and re fixed the demo.

**Comment by indpurvesh** [comment]
Demo should be fixed.
