### ISSUE TITLE
React login page handles the validation error from backend.

### ISSUE THREAD

**Issue by indpurvesh** [avored/avored-rust-cms#120]
we need to handle the validation error on login page. For example when if user do not provide valid email address backend should validate the payload and return the validation errors. and front end should display the error.

**Comment by syazell1** [comment]
- [x] add a client side validation : https://github.com/avored/avored-rust-cms/pull/121

@indpurvesh what are the validation rules for email and password from the login page?
example: email needs to be a valid email & password needs to be alphanumeric, has 1 special characters and 1 capital letter

**Comment by indpurvesh** [comment]
Just keep it simple for now and make validation for minimum 6 char only.
