### ISSUE TITLE
Change password page

### ISSUE THREAD

**Issue by indpurvesh** [avored/avored-rust-cms#141]
We need a page to changed admin user password

**Comment by PritamP20** [comment]
> We need a page to changed admin user password

can you please provide more information, I would like to contribute to the repo

**Comment by indpurvesh** [comment]
@PritamP20 i am glade that you like to contribute. 

Basically I guess I would start with setting up the local environment. 
Add navigation on admin user dropdown. 
create a page in react admin with a form current password and new password and button to submit. 
Backend API to update the password in surrealdb. 

We do have a update password method already which you can call from handler. https://github.com/avored/avored-rust-cms/blob/main/src/services/admin_user_service.rs

If you want i am happy to help you at any stage. Do you want me to assigned it you? 

Thanks

**Comment by srushtiss** [comment]
@indpurvesh I would like to work on this. Can you please assign it to me?

**Comment by indpurvesh** [comment]
@srushtiss  
let me know if you need any help with setting up local setup or anything.

**Comment by srushtiss** [comment]
@indpurvesh May i know what username and password I need to use for .env file?

**Comment by srushtiss** [comment]
> @srushtiss let me know if you need any help with setting up local setup or anything.



> @indpurvesh May i know what username and password I need to use for .env file?

**Comment by indpurvesh** [comment]
Are you talking about SMTP username and password can be left null as it is only used to sent email testing during forgot password email. 

If you want to test that in that case you can create a sandbox account on mailtrap.io website and you will get your own email testing username and password.

**Comment by srushtiss** [comment]
Not that
Error: ConfigMissing("AVORED_DATABASE_NAMESPACE")

**Comment by indpurvesh** [comment]
Basically you just have to rename the `.env.example => .env` in root of the project (rust backend project root)

Admin React Frontend app root: 

root/react-admin/ rename `.env.example => .env` file

**Comment by srushtiss** [comment]
It worked. Thank you.

**Comment by indpurvesh** [comment]
Let me know if you wanted me to work on backend api?
