### ISSUE TITLE
auto fill slugabble in most create ui

### ISSUE THREAD

**Issue by indpurvesh** [avored/avored-rust-cms#212]
React admin make auto fill the sluggable as user type it name 
Below is the url we need to make sure sluggable works 
 - http://localhost:3000/admin/page-create
 - http://localhost:3000/admin/component-create
 - http://localhost:3000/admin/role-create

**Comment by CouldBeFree** [comment]
I want to resolve this issue, but I have some problems with the backend. I have no idea how to set up this file ```data/avored.db```, I get the following error ``` there is an issue with connecting with data/avored.db storage: Ds("Unable to load the specified datastore")```. 
```INFO FOR DB``` returns such response
```-- Query 1 (execution time: 3.224ms)
{
        analyzers: {},
        functions: {},
        models: {},
        params: {},
        scopes: {},
        tables: {
                user: 'DEFINE TABLE user TYPE ANY SCHEMALESS PERMISSIONS NONE'
        },
        tokens: {},
        users: {}
}
```
```INFO FOR NS;``` returns such query
```{
        databases: {
                avored_cms: 'DEFINE DATABASE avored_cms'
        },
        tokens: {},
        users: {}
}
```
@indpurvesh I need your help with db configureation

**Comment by indpurvesh** [comment]
@CouldBeFree  I think i know what is happening. 

Can you please create a `data/avored.db` folder in root of your project. 

<img width="242" alt="Screenshot 2024-08-16 at 8 23 01 AM" src="https://github.com/user-attachments/assets/fa6281bf-bb82-4df0-bec7-35bcd3c952b1">

Then put open your .env file and  put the below values in your `.env file`

     AVORED_DATABASE_NAMESPACE=public
     AVORED_DATABASE_NAME=avored_cms
     AVORED_DATABASE_FOLDER_NAME=file://data/avored.db


I would hope this should fixed the issue.

**Comment by indpurvesh** [comment]
@CouldBeFree  just for your info i did created this bug and will fixed it so other might not have similar issue like you.

**Comment by CouldBeFree** [comment]
Just for clarification. Has this bug been fixed yet? If no, you can assign this issue on me

**Comment by indpurvesh** [comment]
I was referring to the issue regarding the setup issue that you had. Will do some changes to in future other might not face similar issue while setup.

**Comment by CouldBeFree** [comment]
I've successfully started this app. Can you describe your issue more deeply? What do you mean by this ```React admin make auto-fill the sluggable as user type it name```
Maybe I logged in under a user with restricted functionality?
![image](https://github.com/user-attachments/assets/c383673f-f027-42fb-bc1e-3391f0576ac6)
There are some mismatched env
react-admin -> VITE_AVORED_BACKEND_BASE_URL=http://localhost:8080
backend -> AVORED_BACK_END_APP_URL=http://localhost:8081

**Comment by indpurvesh** [comment]
@CouldBeFree  
Sounds good. 

Basically all you have to do is If you are creating a Page and as you type in Name field it should auto fill the identifier field with sluggable. 
<img width="760" alt="Screenshot 2024-08-16 at 5 31 28 PM" src="https://github.com/user-attachments/assets/24291065-5178-4e1b-abd4-88cb1fc4a1db">

Just for your reference i am doing it on component edit page. Take a look at this one.

https://github.com/avored/avored-rust-cms/blob/main/react-admin/src/pages/component/ComponentEditPage.tsx
It does have a function named  `ElementNameOnChange`

Let me know if this is still confusion.

**Comment by indpurvesh** [comment]
Actually I port number 8081 is a new port number I did changed as it was conflicting for me.

**Comment by CouldBeFree** [comment]
> @CouldBeFree Sounds good.
> 
> Basically all you have to do is If you are creating a Page and as you type in Name field it should auto fill the identifier field with sluggable. <img alt="Screenshot 2024-08-16 at 5 31 28 PM" width="760" src="https://private-user-images.githubusercontent.com/4218702/358479455-24291065-5178-4e1b-abd4-88cb1fc4a1db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3OTAyNjAsIm5iZiI6MTcyMzc4OTk2MCwicGF0aCI6Ii80MjE4NzAyLzM1ODQ3OTQ1NS0yNDI5MTA2NS01MTc4LTRlMWItYWJkNC04OGNiMWZjNGExZGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTZUMDYzMjQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTA2ZDFkMDliMDlkODAxMTE1MjJjODcyZjVhYmE5NjE4M2E1OGIwODZlMTQzZTk5YTk5ODE3YjMyNzBiYmJlMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zxPFOkfvg7bFZDLgLyBSPXkdnO4oYNomrDc7xF6jMyE">
> 
> Just for your reference i am doing it on component edit page. Take a look at this one.
> 
> https://github.com/avored/avored-rust-cms/blob/main/react-admin/src/pages/component/ComponentEditPage.tsx It does have a function named `ElementNameOnChange`
> 
> Let me know if this is still confusion.

I have several points to discuss

1. test page e.r. test-page; some new page e.r. some-new-page
2. Does the identifier field should be editable? I think that the user should be able to update the slug for some possible SEO improvements

**Comment by indpurvesh** [comment]
Yes you are right. Identifier field is always editable.

**Comment by indpurvesh** [comment]
Yes your point 1 is exactly right too.

**Comment by CouldBeFree** [comment]
Assign this issue to me please

**Comment by CouldBeFree** [comment]
> React admin make auto fill the sluggable as user type it name Below is the url we need to make sure sluggable works
> 
> * http://localhost:3000/admin/page-create
> * http://localhost:3000/admin/component-create
> * http://localhost:3000/admin/role-create

I have already fixed issues on this page, but I have several points to improve
1. Why user is not able to remove the page?
![image](https://github.com/user-attachments/assets/76a71451-43c9-4ff1-85c7-f524ee964941)
2. if there are not enough items to paginate, pagination should not be rendered, and it is not readable due to the blue color
![image](https://github.com/user-attachments/assets/362bd16f-ee53-490d-b99d-bc9a333b2527)
3. Why user can't edit the slug on the edit page? I think it should be editable
![image](https://github.com/user-attachments/assets/304a4d03-65c3-4dea-92f5-9a54367df618)
4. The user should be able to filter the table by params like name, identifier etc.

@indpurvesh if you ok with such improvements, I can implement them in the same PR, or you can create separate issues.

**Comment by indpurvesh** [comment]
@CouldBeFree 

Point 1: Yes right now there is no delete yet. If you can add a front end confirmation modal then i am happy to do backend api.

Point2: In regards with pagination i think button should be thee but just the css is wrong.. It would be more better if we keep the button visible but make it `disabled` and make the `opacity 0.4` or `0.5` as it looks disabled. ( should look disabled).

Point3: Identifier is editable once you click on `edit identifier` 

Point4: Yes all the table should be filterable if you can work on frontend. I am happy to do backend.

**Comment by CouldBeFree** [comment]
@indpurvesh, thank you for your response. 
First of all, I will submit a PR with the current changes. Regarding points 1, 2, and 4, if you don't mind, I can implement the backend API along with the frontend myself. If you're okay with it, I will create separate issues for each and assign them to myself.

**Comment by indpurvesh** [comment]
@CouldBeFree  

Please don't work on asset filter or anything in regards with asset for point no 1, 2 and 4. ( Just giving you an update only).

I am thinking to display asset in grid not with tables. Will worked on Asset remove api too.

**Comment by CouldBeFree** [comment]
> @CouldBeFree
> 
> Please don't work on asset filter or anything in regards with asset for point no 1, 2 and 4. ( Just giving you an update only).
> 
> I am thinking to display asset in grid not with tables. Will worked on Asset remove api too.

U didn't get your point. Can I wirk on issues I mentioned here https://github.com/avored/avored-rust-cms/issues/212#issuecomment-2294648651 including backend but without table filter?
