### ISSUE TITLE
Admin should be allowed to delete record in admin.

### ISSUE THREAD

**Issue by indpurvesh** [avored/avored-rust-cms#216]
We need to add an delete feature for admin to delete records in the system.

**Comment by CouldBeFree** [comment]
Assign this to me

**Comment by indpurvesh** [comment]
Just throwing an idea here... Do you think it would be better to not to delete a DB record and make the DB record as delete_at = time::now() ? instead of delete the record from database? 

What do you think?

**Comment by CouldBeFree** [comment]
So your point is not to delete the page (as an example), but simply mark it as 'deleted'? If yes, this is not helpful, but I can be wrong. In WP for example, if you decide to remove the page it will be removed permanently

**Comment by indpurvesh** [comment]
Yes you right just make as deleted. 

At this point yes we delete the record too. But might need to think about if the page was published then may be Delete is not allowed or something. This could be for future so now just delete the record.

**Comment by CouldBeFree** [comment]
We can implement two options

1. Delete permanently
2. Archive page
So user would be able to make the choice by himself, what he wants to do with the page. If the user selects the archive option, he will be able to restore the page.
@indpurvesh what do you think?

**Comment by indpurvesh** [comment]
Good idea.may be for now we can simply delete the record. Very good point
