### ISSUE TITLE
Website for Avored rust cms 

### ISSUE THREAD

**Issue by indpurvesh** [avored/avored-rust-cms#23]
We need to build a simple html / css based website for avored rust. 

https://github.com/avored/avored-rust-cms/blob/main/docs/index.html

**Comment by rameshvoodi** [comment]
hello @indpurvesh i can work on this, can you explain more about the website

**Comment by indpurvesh** [comment]
@rameshvoodi sure you can work on it. 
Are you thinking of doing static site only? Or vue or react?

**Comment by rameshvoodi** [comment]
@indpurvesh  sure, what info should i add , any references would help

**Comment by indpurvesh** [comment]
@rameshvoodi it would be good to start with setting up basic layout with some lorelipsum content . I will work / think about the content part of the website. 

Below is the list that I think of adding features 
 - Admin Users
 -  Roles/Permissions
 - Components
 - Pages
 -  Collection
 - SEO
 -  Asset Manager
 - Content Workflow builder
 -

**Comment by indpurvesh** [comment]
@rameshvoodi 
Take a look at this file I did a very quick layout `https://github.com/avored/avored-rust-cms/blob/main/docs/index.html`

there is a lot of improvement that needs to be done. I guess it is just a starting point. Hope it helps.

**Comment by indpurvesh** [comment]
Very basic website is done. Will improve as it goes. ..

[Avored website](https://www.avored.com)
