### ISSUE TITLE
Add some stacktrace info or some more logs when general error occur

### ISSUE THREAD

**Issue by dejavuwl** [avored/avored-rust-cms#241]
Should stacktrace be printed [here](https://github.com/avored/avored-rust-cms/blob/c2a23d29acda62ab86f8b6cc0504e535068fcde6/src/error.rs#L170C1-L171C1)?
Otherwise, it will only show 'test 500' in response body and no error info in console or log file.

**Comment by indpurvesh** [comment]
@dejavuwl as i understand you would be able to see the error in `public/log/avored.log` file when the 500 error is generate


    impl From<std::io::Error> for Error {
        fn from(val: std::io::Error) -> Self {
            error!("there is an issue with creating io error: {val:?}"); // this line will go in the log file. 
            Error::Generic("tokio file create folder error ".to_string())
        }
}

**Comment by dejavuwl** [comment]
Thanks a lot, i found the log in `public/log/avored.log`.
