### ISSUE TITLE
Display success message

### ISSUE THREAD

**Issue by indpurvesh** [avored/avored-rust-cms#33]
Display success message after 
 - [x] Create Admin User
 - [x] Edit Admin User
 - [x] Delete Admin User
 - [x] Create Role
 - [x] Edit Role
 - [x] Delete Role

**Comment by subhajit20** [comment]
@indpurvesh  hey want to help. could you assign it to me?

**Comment by indpurvesh** [comment]
@subhajit20  sure will assign it to you.

here is the code that I think will work. Haven't tested it yet. 

`store_admin_user_handler.rs`
 
    session
        .insert("success_message", "Admin User added successfully!")
        .expect("Could not store the validation errors into session.");

**Comment by subhajit20** [comment]
Is this the right place to put this @indpurvesh ?

![store_admin_user_handler rs - avored-rust-cms  Codespaces_ solid acorn  - Visual Studio Code - Google Chrome 10-09-2023 16_05_42](https://github.com/avored/avored-rust-cms/assets/99127578/1e28c088-f67b-4549-b449-a4e29247b929)

**Comment by indpurvesh** [comment]
@subhajit20 

Yes it looks right. 
Few more points. 

- Update the except message.
- add `mut` for session
- add `pub success_message: String` in ViewModel of `admin_user_table_handler.rs`

But you looks to be on right track.

**Comment by subhajit20** [comment]
@indpurvesh Hey, made a PR.
can you check and let me know for furthur correction?

**Comment by indpurvesh** [comment]
@subhajit20 have you tested it?

**Comment by subhajit20** [comment]
I could not find this `avored-cms/rust-api`  folder. Unable to run the application

**Comment by subhajit20** [comment]
this following error comming 
`process didn't exit successfully: `/workspaces/avored-rust-cms/target/debug/build/librocksdb-sys-361202dacf34b68c/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'Unable to find libclang: "couldn't find any valid shared libraries matching: ['libclang.so', 'libclang-*.so', 'libclang.so.*', 'libclang-*.so.*'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.65.1/lib.rs:603:31`

**Comment by indpurvesh** [comment]
@subhajit20  sorry. ReadME is an older version. will update you soon. 

Just let you know in advanced. Once the application start then you have to visit 

`http://localhost:8080/setup` this url will create database tables and admin user once you submit it. 

Looks like your issue is related to you don't have a c++ compiler installed.


https://users.rust-lang.org/t/unable-to-find-libclang-the-libclang-issue/70746



<img width="754" alt="Screenshot 2023-09-10 at 11 09 58 PM" src="https://github.com/avored/avored-rust-cms/assets/4218702/845e9500-9304-467a-b01a-72eb05a53e48">

**Comment by subhajit20** [comment]
@indpurvesh Hey I fixed that but after successful login no message is being shown instead redirected to login page

**Comment by indpurvesh** [comment]
@subhajit20 


After setup haven't added a result page which should display a success message and link to an admin login page.  Few other information like docs etc.

**Comment by indpurvesh** [comment]
Good work @subhajit20
