### ISSUE TITLE
unique validation

### ISSUE THREAD

**Issue by indpurvesh** [avored/avored-rust-cms#38]
we need to add a unique validation for 
 - [x] create role
 - [x] update role

**Comment by tu6ge** [comment]
Maybe, this library (https://docs.rs/valitron/latest/valitron/) should be help you , this  is a functional validator

**Comment by indpurvesh** [comment]
@tu6ge  thanks for the suggestion. I am using the same one. 

https://github.com/avored/avored-rust-cms/blob/main/src/api/admin_user/requests/authenticate_admin_user_request.rs

**Comment by tu6ge** [comment]
yeah, now you are having new  option

**Comment by indpurvesh** [comment]
unique validation is done with seperate with editable from edit pages
