### ISSUE TITLE
Show Component with fields

### ISSUE THREAD

**Issue by indpurvesh** [avored/avored-rust-cms#48]
display comment fields on show component page.

**Comment by RP99** [comment]
Hi @indpurvesh,

If this issue is still open, I would like to contribute.

Thanks.

**Comment by indpurvesh** [comment]
@RP99 


Sure you can take it. 

If you can improve the design of how we render the information that would be great. 

Currently Looks Like:

<img width="1201" alt="Screenshot 2023-10-15 at 11 41 37 AM" src="https://github.com/avored/avored-rust-cms/assets/4218702/09d002a9-ecd1-4069-8250-694604178558">

Let you know that as i remember last time query should return the component with the attached fields list.  
If you can come up with any idea that will improve the design that will be helpful.

**Comment by RP99** [comment]
Can you kindly explain easy way to do it.

**Comment by indpurvesh** [comment]
Question.. Do you have a local setup done?

**Comment by RP99** [comment]
I haven't setup locally and I don't have any experience with Rust. So, is the work going to involve Rust or CSS? If it's going to involve only Rust then you can go ahead an unassign me!

**Comment by indpurvesh** [comment]
@RP99  if you want you can still do and update the html / css piece with fake data. then I can make it dynamic. But either case you still need local setup.  Let me know you can do a local setup or not. if not then must be very hard to check what you have done?

**Comment by RP99** [comment]
Ok, in that case - let me try to set up locally

**Comment by RP99** [comment]
I have finally set up. However, I can't is not going beyond login pagehttp://localhost:8080/admin/login

**Comment by RP99** [comment]
I have finally set up locally. However, I can't go beyond login page [http://localhost:8080/admin/login](http://localhost:8080/admin/login) and I am seeing following:
![image](https://github.com/avored/avored-rust-cms/assets/11474234/2dc34aa0-95fa-425e-89e9-274b61a8b2ee)

**Comment by indpurvesh** [comment]
To me, it feels like you are missing the database creation process. 

Try visiting `localhost:8080/setup` and then press submit. (it should create the database tables and admin users once you do that then I guess you do not see this 500 error.  Let me know how it goes.? 

Thanks

**Comment by RP99** [comment]
Previous problem is now solved. So, can you kindly clarify the requirement regarding show component page.

**Comment by indpurvesh** [comment]
Idea here is that Components details needs to display components all the details like
 - name
 - identifier
 -  fields list
     - text field
     - dropdown field
     - image
     - checkbox
     - radio 
     - etc ... etc
I would suggest you can just do a html/css with dummy names/details of components once you do a pull request.

The tricky part here is you have to come up with a design or idea of how to display the above information better way so it makes sense. You just need to think more of a UI/UX perspective.

**Comment by indpurvesh** [comment]
closing the issue not required.
