### ISSUE TITLE
React Input component

### ISSUE THREAD

**Issue by indpurvesh** [avored/avored-rust-cms#87]
we need to build an react input component to reduct the code duplication in the app

**Comment by nitesh32** [comment]
I can help with component creation in react.

**Comment by indpurvesh** [comment]
@nitesh32  do you want me to assign it to you?

**Comment by nitesh32** [comment]
Thanks @indpurvesh for assigning me this issue.

**Comment by nitesh32** [comment]
Hey @indpurvesh can you plz explain me more about the issue with screenshots where do you want add new component in app?

**Comment by indpurvesh** [comment]
@nitesh32 
It is a basic input field components it might be used almost every where we display a text field. 

For example Login screen input field.

<img width="613" alt="Screenshot 2023-12-22 at 7 42 54 AM" src="https://github.com/avored/avored-rust-cms/assets/4218702/404cfdce-17f4-4524-b192-254cae668bb2">

**Comment by rohan-bhautoo** [comment]
Hello @indpurvesh, can you assign me this issue please? Pull Request has already been created.
